[package]
name = "cURLtui-rs"
version = "0.1.0"
authors = ["PThorpe92 <preston.thorpe@maine.edu>"]
license = "GPL-3.0"
edition = "2021"

[dependencies]
crossterm = "0.26.1"
tui = { package = "ratatui", version = "0.21.0" }
tui-widget-list = "0.2.2"
