[package]
name = "cURLtui-rs"
version = "0.1.0"
authors = ["PThorpe92 <preston@unlockedlabs.org>"]
license = "GPL-3.0"
edition = "2021"

[dependencies]
reqwest = "0.11.20"
crossterm = "0.27.0"
tui = { package = "ratatui", features = ["crossterm"], version = "0.21.0" }
tui-input = "*"
tui-widget-list = "0.2.2"
lazy_static = "1.4.0"
